src/packages/button/__test__/__snapshots__/button.spec.tsx.snap
src/packages/button/button.tsx
src/packages/popover/Trigger.tsx

1、修改了按钮服务端渲染的时候不渲染class和style的问题
2、调整了class生成的字符串换行的问题
3、修改Trigger TS校验错误
by liujianchuan

fix: 修改Button在服务端不渲染class和style

---

src/config.json
src/packages/imagepreview/demo.taro.tsx
src/packages/imagepreview/imagepreview.scss
src/packages/imagepreview/imagepreview.taro.tsx
src/packages/imagepreview/imagepreview.tsx
src/packages/swiper/swiper.scss
src/packages/swiper/swiper.taro.tsx
src/sites/mobile-taro/src/app.config.ts

包含以下修改：
1、imagepreview.scss 中增加 popup、swiper、video 样式导入
2、imagepreview demo.taro 中移除 video 组件的使用（不支持）
3、修改 imagepreview 中使用 swiperItem 的方式，兼容 swiper 内部关于 children 的操作
4、swiper 中 useEffect 内调用 init 时增加 nextTick，解决 imagepreview 无法获取 rect 的问题

feat: imagepreview 适配 taro

---

src/packages/radio/radio.tsx

fix: radio 组件中的 render 数组改成 fragment

---

src/packages/timeselect/demo.taro.tsx
src/packages/timeselect/demo.tsx
src/packages/timeselect/doc.en-US.md
src/packages/timeselect/doc.md
src/packages/timeselect/doc.zh-TW.md
src/packages/timeselect/timeselect.taro.tsx
src/packages/timeselect/timeselect.tsx

feat: timeselect 组件增加 onSelect onPannelChange onTimeChange 事件

---

src/packages/tabs/demo.taro.tsx
src/packages/tabs/demo.tsx
src/packages/tabs/doc.en-US.md
src/packages/tabs/doc.md
src/packages/tabs/doc.zh-TW.md
src/packages/tabs/tabs.scss

日常 bug 修复
之前支持的css粘性布局 更改了 页面结构，没有考虑到对左右布局样式的影响，以及 tab标签部分 标签过多并且没有开启滚动支持情况下，页面宽度超出问题。
此次提交 主要修复以上问题，并补充了左右布局demo部分样式，与vue版本demo对齐。

fix: 支持css粘性布局，引起的左右布局bug修复

---

src/packages/datepicker/doc.md

#448 
链接 https://nutui.jd.com/react/#/zh-CN/component/datepicker 例子7 过滤选项,跳转至代码平台后，预览框无法渲染，看到控制台报错 `ReferenceError: desc6 is not defined`。修改desc6 为desc7 后正常运行

docs: 修复 datepicker 文档中示例代码错误

---

src/packages/formitem/formitem.taro.tsx
src/packages/formitem/index.taro.ts

fix: nutui-react-trao 移除 formitem 对 react-router-dom 的依赖

---

src/packages/collapse/collapse.taro.tsx
src/packages/collapse/collapse.tsx
src/packages/collapseitem/collapseitem.taro.tsx
src/packages/collapseitem/collapseitem.tsx

close #508
https://github.com/jdf2e/nutui-react/issues/508
1、Collapse组件数据修改后组件不刷新 #508
2、监听组件children发生变化 渲染组件

fix: #508 修改折叠面板组件修改后不刷新问题

---

package.json
rollup.config.es.js
rollup.config.taro.es.js
src/packages/configprovider/configprovider.taro.tsx
src/packages/configprovider/configprovider.tsx

chore: nutui taro 在 iOS 11 下和 taro 的 regenerator-runtime 冲突

---

src/packages/tag/__test__/__snapshots__/tag.spec.tsx.snap
src/packages/tag/__test__/tag.spec.tsx
src/packages/tag/doc.en-US.md
src/packages/tag/doc.md
src/packages/tag/doc.taro.md
src/packages/tag/doc.zh-TW.md
src/packages/tag/tag.scss
src/packages/tag/tag.taro.tsx
src/packages/tag/tag.tsx
src/styles/variables.scss

存在问题：
同时使用 type、color、plain 时，生成样式的逻辑错误。
本次提交包含以下内容：
1、修改样式生成逻辑，与 NutUI-Vue 保持一致
2、移除多余的样式变量及其文档说明
3、更新了单元测试
4、优化了 Tag 类名生成逻辑
效果图：

fix(tag): 修复 plain 与 type 同时使用时的样式错误

---

src/packages/formitem/formitem.tsx

fix: 修复FormItem代理子元素onChange后忽略了原属性的问题 

---

src/packages/audio/audio.taro.tsx
src/packages/backtop/backtop.taro.tsx
src/packages/barrage/barrage.taro.tsx
src/packages/cell/cell.taro.tsx
src/packages/drag/drag.taro.tsx
src/packages/elevator/elevator.taro.tsx
src/packages/searchbar/searchbar.taro.tsx
src/packages/uploader/uploader.taro.tsx
src/packages/virtuallist/virtuallist.taro.tsx

在 Taro 项目，通过 npm run dev:h5 启动后，组件内部通过 import Taro from ‘@tarojs/taro' 使用的 API 有可能会报错。主要是因为 Taro 在 H5 环境会将 ‘@tarojs/taro’ 解析到 ‘@tarojs/taro-h5‘，然而这个库并不是导出所有的 API。
Taro-H5 实际并没有在 Taro 对象上挂载所有的 API，这是为了避免不必要的 API 占用包体的大小，那么为了兼容小程序的 API 使用方法就需要对开发者的代码在编译前做出一些调整。https://taro-docs.jd.com/docs/external-libraries#babel

fix: 修复 taro h5 有些 api 未导出导致报错

---

src/packages/ellipsis/__test__/ellipsis.spec.tsx
src/packages/ellipsis/ellipsis.tsx

问题描述：Ellipsis组件在content较少（不足以触发展示省略号逻辑时），多次修改content会触发内存泄露（创建的dom一直保留在body内，没有删除）
复现代码：
```
const [count, setCount] = useState(0)
useEffect(() => {
const timer = setInterval(() => {
setCount(count + 1)
}, 1000)
return () => clearInterval(timer)
})
<Ellipsis content={`${count}`} direction="end" />
```
改动点：
1. calcEllipse执行完后，直接把container移除（因为后面已经没有地方再需要使用container了）
2. useEffect里把`document.body.appendChild(container)`移除，这行代码似乎是多余的？
3. 增加内存泄露测试用例

fix(ellipsis): ellipsis内存泄露

---

src/packages/col/col.taro.tsx
src/packages/col/col.tsx
src/packages/row/row.taro.tsx
src/packages/row/row.tsx

#682 
解决方案
- 使用项目依赖的 `classnames` 包的默认方法，可以兼容缺省的 `className` props ，当 `className` 为 `undefiend` 时则不会被添加到元素的类名中。

fix(layout): 修复布局组件 `Row` 和 `Col` 的 className 设置问题

---

src/packages/textarea/textarea.taro.tsx

https://github.com/jdf2e/nutui-react/issues/672
Taro 提供的 plugin-html 插件中会对一些认为是特殊属性的属性进行处理，对于 textarea 的处理来说，disabled 和 readonly 都映射到一个上面，所以当 disabled设置为true，readonly 设置为 false，则 textarea 可以输入内容

fix: textarea 禁用状态仍然可以输入

---

src/packages/shortpassword/demo.taro.tsx
src/packages/shortpassword/demo.tsx
src/packages/shortpassword/doc.en-US.md
src/packages/shortpassword/doc.md
src/packages/shortpassword/doc.taro.md
src/packages/shortpassword/doc.zh-TW.md
src/packages/shortpassword/shortpassword.taro.tsx
src/packages/shortpassword/shortpassword.tsx

当前shortpassword组件不支持自动聚焦，每次弹出短密码输入框时，都需要用户手动点击一下才能输入密码，比较不方便，希望能增加`autoFocus`属性以支持自动聚焦，默认为false。

feat(shortpassword): 支持自动聚焦

---

src/packages/cascader/cascader.taro.tsx
src/packages/cascader/cascader.tsx
src/packages/cascader/cascaderItem.taro.tsx
src/packages/cascader/cascaderItem.tsx

https://github.com/jdf2e/nutui-react/issues/695
Cascader 组件使用了 forwardRef ，但是缺少了 ref 参数，导致出现 waring 信息

fix: cascader 没有传递 ref 参数

---

src/packages/ellipsis/demo.taro.tsx
src/packages/ellipsis/demo.tsx
src/packages/ellipsis/ellipsis.taro.tsx
src/packages/ellipsis/ellipsis.tsx

https://github.com/jdf2e/nutui-react/issues/692
ellipsis 组件的 onClick 加在最外层的 HTML 标签上，展开和关闭的 HTML 在内层，并且带有 onClick 事件，不过并没有加阻止冒泡的处理，导致展开和关闭点击的时候会触发父元素的 onClick

fix: ellipsis 展开和关闭操作应该阻止事件冒泡

---

src/packages/checkbox/doc.en-US.md
src/packages/swipe/demo.taro.tsx
src/packages/swipe/demo.tsx
src/packages/swipe/doc.en-US.md
src/packages/swipe/doc.md
src/packages/swipe/doc.taro.md
src/packages/swipe/doc.zh-TW.md
src/packages/swipe/swipe.taro.tsx

https://github.com/jdf2e/nutui-react/issues/505
已经实现了实例上的 open 和 close 方法，但是在文档和 Demo 中未体现。基于 taro 的实现计算宽度时机错误，已修复。

feat: swipe 组件对外暴露 open 和 close 方法，优化 taro 版本下 width 的计算时机

---

src/packages/animatingnumbers/__tests__/animatingnumbers.spec.tsx
src/packages/animatingnumbers/countup.tsx

问题：`AnimatingNumbers.CountUp` 组件设置`delaySpeed`属性不生效。
原因：`CountUp`组件里有两个`useEffect`调用了`setNumberTransform`，导致第一个useEffect（使用了delaySpeed那个）是无效的。
修改点：
1.  把两个`useEffect`合并成一个
2. `numerArr`使用了`useMemo`，可以避免重新渲染时不必要的`setNumberTransform`调用

fix(animatingnumbers): 修复delaySpeed不生效

---

src/packages/table/demo.taro.tsx
src/packages/table/demo.tsx
src/packages/table/doc.en-US.md
src/packages/table/doc.md
src/packages/table/doc.taro.md
src/packages/table/table.taro.tsx
src/packages/table/table.tsx
src/packages/table/types.ts

https://github.com/jdf2e/nutui-react/issues/795

feat: 表格支持隐藏表头属性

---

src/packages/radiogroup/radiogroup.scss

https://github.com/jdf2e/nutui-react/issues/768
针对 radiogroup 的 button 增加激活状态的样式

fix: radiogroup 中使用 button 类型的 radio 样式不对

---

src/packages/textarea/textarea.taro.tsx
src/packages/textarea/textarea.tsx

taro 版本中，给 textarea 设置 maxlength 后，通过中文输入法进行输入，拼音长度超过剩余可输入字符数的话，无法回填。
解决办法：
在 textarea 中去掉了 maxlength 属性的设置，通过 input 事件和 maxlength 做截断，如果截断后的数据一致，则强制更新。

fix: textarea 优化中文输入

---

src/packages/ellipsis/ellipsis.taro.tsx

https://github.com/jdf2e/nutui-react/issues/786
在 taro 版本中 useLayoutEffect 替换为 useReady

fix: ellipsis 在深层嵌套中无法获取元素信息

---

src/styles/variables.scss

https://github.com/jdf2e/nutui-react/issues/777
在 https://github.com/jdf2e/nutui-react/pull/688 中修改了 textarea 的 padding。导致和 vue 版本的视觉不一致。

fix: 修改 textarea 的 padding 为之前版本的值

---

src/packages/picker/picker.taro.tsx

<https://github.com/jdf2e/nutui-react/issues/828>

fix: picker 组件在小程序端触发滚动后，页面(有滚动条的情况下)也一起滚动

---

src/packages/tabs/tabs.taro.tsx

https://github.com/jdf2e/nutui-react/issues/869

fix: tabs 组件paneKey为空字符串时返回索引问题

---

src/packages/griditem/griditem.taro.tsx

https://github.com/jdf2e/nutui-react/issues/871

fix: grid-item 组件设置 className 后丢失了原有的 nut-grid-item 样式类
